### ISSUE TITLE
double typing in SQL console

### ISSUE THREAD

**Issue by Efpophis** [ok2cqr/cqrlog#108]
Each typed character appears twice in SQL console window.

1. Navigate to Filter->SQL Console
2. Try typing in a query, i/e: "select * from log_changes"

You'll get 2 of each letter as you type.

Fortunately, backspace isn't duplicated, so one may form queries by deleting the extra letter each time.

**Comment by OH1KH** [comment]
Hi
See this:
https://cqrlog.com/node/2064

-- 
Saku
OH1KH   

5. heinäkuuta 2018 16.11.22 GMT+03:00 Bill Crossley <notifications@github.com> kirjoitti:

**Comment by Efpophis** [comment]
Thanks! Found the workaround, so I will close this issue out.
