### ISSUE TITLE
Cqrlog license ?

### ISSUE THREAD

**Issue by hasorli** [ok2cqr/cqrlog#119]
I suggest that Cqrlog include a license.  Preferable some sort of Open source license. 

https://choosealicense.com/

**Comment by ok2cqr** [comment]
CQRLOG is licenced under GPL 2.0

**Comment by gl-bars** [comment]
Note: COPYING has to be in the root to be displayed in the repository overview by GitHub

**Comment by dl7oap** [comment]
i suggest to close this issue. its already fixed.
