### ISSUE TITLE
ADIF import: duplicates detection does not work

### ISSUE THREAD

**Issue by gl-bars** [ok2cqr/cqrlog#124]
Due to broken logic the QSO duplicates check will never be called:

```
First : Boolean = False;
...
if First then
begin
  First := False;
```

Also duplicates lookup can probably be optimized: instead of creating a query every time the same query could be reused with dataset functions like Locate or Lookup:

```
if Q.Locate('qsodate;time_on;callsign', VarArrayOf([d.QSO_DATE, d.TIME_ON, d.CALL]), []) then ...
```

where Q is a suitable cqrlog_main select query.

**Comment by dl7oap** [comment]
Hello, 
duplicate check can now be activated via checkbox in the import start dialog.
for easy handling i translate the function names to english.

Q.Locate is slower then a sql, particulare when you have big logfiles (>100.000 QSO and more), so i did not implement that.

Suggestions:
- Maybe you can speed up with bulk uploads and not individual INSERTS
- Maybe you can speed up by having the duplicate check in a dynamic list parallel to the database with DATE; TIME; CALL so only access to memory but not to database have to be done

i think this issue can be closed when my pull request is merged.
