### ISSUE TITLE
DXCC list fails to show worked countries

### ISSUE THREAD

**Issue by OH1KH** [ok2cqr/cqrlog#166]
DXCC list fails to show worked countries properly.
If user has manually edited qsl received and accidentally typed space preceeding "Q" system does not trim the column and leads DXCC list error(s) not counting those entries.

I also suspect that table lines  country/band does not fill columns in proper way.
Sometimes there is L , sometimes LL, sometimes XX at same band column.No explanation does it mean different modes or different way of confirms (card, lotw,eqsl) at same band.

**Comment by dl7oap** [comment]
Hi, 
1) solved by trim at lostfocus in gui on qslr and qsls
2) helpfile updated to clearify meaning of E and L. X and Q and the three positions of letters are already explained in helpfile  (PHONE - CW - DIGI)
