### ISSUE TITLE
There is no limit check at NewQSO fields

### ISSUE THREAD

**Issue by OH1KH** [ok2cqr/cqrlog#168]
There is no limit check at NewQSO fields.
For example if user enters incredible long "Name", or gets it by fetch result from HamQth or Qrz saving the qso results error:
Error executing query. Data too long for column 'name' at row 1

There are also other fields where input length is not fixed with database column length.

**Comment by dl7oap** [comment]
Todo: Setting TEdit.MaxLength Attribute of Inputfields and maybe a mouse-over comment (TEdit.ShowHint = True and TEdit.Hint = "Text") with a hint of maximal allowed length.
