### ISSUE TITLE
DEB in PPA fails with dependencies of mysql, works with mariadb

### ISSUE THREAD

**Issue by stdevPavelmc** [ok2cqr/cqrlog#291]
Tested in Ubuntu EOAN and FOCAL (eoan version and source code compilation)

If you install the deb from the PPA it will prefer to install

```
mysql-server, mysql-server-8.0 and mysql-client-8.0
```

But in the tested environments that is a fail, as the configs are not able to bring up the database server see #289, not with a old profile or with a non existent one (forcing creation of one)

Deb dependencies must be set to:

```
mariadb-server mariadb-server-10.3 mariadb-client-10.3
```

by default and all all works like a charm

**Comment by ok2cqr** [comment]
Already fixed. Since version 2.5 cqrlog depends on mariadb instead of MySQL.
