### ISSUE TITLE
Online log upload settings

### ISSUE THREAD

**Issue by OH1KH** [ok2cqr/cqrlog#320]
I am not user of online logs so I ask comments for this action (that feels strange to me):

If user has filled any online log details with his call and other information and checked "Upload qso data immediately...." but then **unchecked** "Enable upload to ....." that I understand that he does not use uploading now.

Then when adding or editing qso he is prompted by cqrlog all the time that he should enable uploading.

User can not set his data or "Upload qso data immediately...."  if "Enable upload to ....."  is first checked as fields are grayed out. So entering information and then checking **out** "Enable upload to ....." user wants to keep his data there, but temporary disable uploads. 

He should well know that upload will not happen and he should not be prompted by cqrlog every time qso data changes.
That is what I think.

But need your comments should this be fixed?

**Comment by phl0** [comment]
I cannot see the issue at the moment. If you disable the "Enable upload to xxx" I suggest that no data at all should be uploaded anywhere. So why should the user be asked to upload if the upload is disabled by general?
