### ISSUE TITLE
uVersion.pas

### ISSUE THREAD

**Issue by OH1KH** [ok2cqr/cqrlog#334]
It has been a while since last official release and lots of fixes and features has been added.
It also seems that part of users are able to compile cqrlog from source with proper instructions.

When problems arise we really can not be sure what version user is now using. Debug dump is showing version number and date that is always the official release version and date.

May I suggest that for now on new pull requests have uVersion.pas changed to have date of pull request. Then we have some kind of track what the user version really is.

Comments?

**Comment by phl0** [comment]
I like the idea. Would aid debugging.
