### ISSUE TITLE
QRZ callbook query returns name only

### ISSUE THREAD

**Issue by peterdulowsky** [ok2cqr/cqrlog#355]
I am quite new to CQRLOG, compiled it from the source about 2 weeks ago. I spotted that when the QRZ callbook is selected only name gets updated. The other info like QTH, grid square e.t.c. do not. With HAMQTH it all works just fine. I suspect this is an issue with parsing data from QRZ.

**Comment by OH1KH** [comment]
Hi !
Have you paid for QRZ use ?
Without payment it shows only basic information.

https://www.qrz.com/page/xml_data.html

**Comment by peterdulowsky** [comment]
My bad, i did not realize that.
