### ISSUE TITLE
EDI export bands 2m 70cm?

### ISSUE THREAD

**Issue by OH1KH** [ok2cqr/cqrlog#472]
Thomas, SM0KBD, states an issue in EDI export https://www.cqrlog.com/node/3288

By IARU R1 handbook bands should be 145MHz and 435MHz

By http://www.ok2kkw.com/ediformat.htm  bands are 144MHz and 432MHz.

As I have never used EDI (had my last 2m/70cm contest station in 1990's and the paper logs were used then) and I am not sure do we have to count differences with Regions 1, 2 and 3 or is EDI used only in Region 1 contests?

By thinking of that can we change those without doing harm to R2 and R3 users?
 
Comments?

**Comment by phl0** [comment]
I did notice that but hand-edited my .edi files :) For R1 it would make sense I assume.
